# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policy_Year', models.CharField(max_length=20)),
                ('TID_No', models.CharField(max_length=20)),
                ('Patient_Name', models.CharField(max_length=150)),
                ('Present_Pkg_Status', models.CharField(max_length=150)),
                ('Hosp_Name', models.CharField(max_length=150)),
                ('Adm_Date', models.CharField(max_length=150)),
                ('Disch_Date', models.CharField(max_length=150)),
                ('Pkg_Code', models.CharField(max_length=20)),
                ('Pkg_Name', models.CharField(max_length=500)),
                ('Pkg_Rate', models.IntegerField(default=0)),
                ('Pkg_Cat', models.CharField(max_length=20)),
                ('Dist_Name', models.CharField(max_length=20)),
                ('Id_Type', models.CharField(max_length=20)),
                ('Identity_No', models.CharField(max_length=20)),
                ('Verified_Aadhar_No', models.CharField(max_length=20)),
                ('Hospital_Type', models.CharField(max_length=25)),
                ('Hospital_Code', models.CharField(max_length=20)),
                ('Admission_Time', models.CharField(max_length=150)),
                ('Discharge_Time', models.CharField(max_length=150)),
                ('Last_Mod_Date', models.CharField(max_length=150)),
                ('Net_Paid_Amt', models.IntegerField(default=0)),
            ],
        ),
    ]
