# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_datamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='Adm_Date',
            field=models.CharField(db_column='Adm Date', max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Admission_Time',
            field=models.CharField(db_column='Admission Time', max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Disch_Date',
            field=models.CharField(db_column='Disch Date', max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Discharge_Time',
            field=models.CharField(db_column='Discharge Time', max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Dist_Name',
            field=models.CharField(db_column='Dist Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Hosp_Name',
            field=models.CharField(db_column='Hosp Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Hospital_Code',
            field=models.CharField(db_column='Hospital Code', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Hospital_Type',
            field=models.CharField(db_column='Hospital Type', max_length=25),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Id_Type',
            field=models.CharField(db_column='Id Type', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Identity_No',
            field=models.CharField(db_column='Identity No', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Last_Mod_Date',
            field=models.CharField(db_column='Last Mod Date', max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Net_Paid_Amt',
            field=models.IntegerField(db_column='Net Paid Amt', default=0),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Patient_Name',
            field=models.CharField(db_column='Patient Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Pkg_Cat',
            field=models.CharField(db_column='Pkg Cat', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Pkg_Code',
            field=models.CharField(db_column='Pkg Code', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Pkg_Name',
            field=models.CharField(db_column='Pkg Name', max_length=500),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Pkg_Rate',
            field=models.IntegerField(db_column='Pkg Rate', default=0),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Policy_Year',
            field=models.CharField(db_column='Policy Year', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Present_Pkg_Status',
            field=models.CharField(db_column='Present Pkg Status', max_length=150),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='TID_No',
            field=models.CharField(db_column='TID No', max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='Verified_Aadhar_No',
            field=models.CharField(db_column='Verified Aadhar No', max_length=20),
        ),
    ]
